# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import typing
from xenosite.forest import mol
__all__ = [
    "BoundPattern",
    "Emission",
    "EmissionDict",
    "ForestMol",
    "Formula",
    "GraphEdge",
    "GraphEdgeDict",
    "GraphNode",
    "GraphNodeDict",
    "HopDict",
    "MaybeEntryDict",
    "MetabolicNetwork",
    "PathCounters",
    "PathCountersDict",
    "PathOutcome",
    "PathOutcomeDict",
    "PatternInfo",
    "PatternSummaryDict",
    "PlanStepDict",
    "RandomPathOutcome",
    "RandomPathOutcomeDict",
    "RandomPathStepDict",
    "ResidualDict",
    "RuleSet",
    "StepPlan",
    "StepPlanDict",
    "dealkylation",
    "default_ruleset",
    "dehydrogenation",
    "epoxidation",
    "epoxide_opening",
    "expand_iri",
    "find_path",
    "find_path_partial",
    "forest_xmet_sssom",
    "hydrolysis",
    "hydroxylation",
    "leaf_rule",
    "n_dealkylation",
    "normalize_tautomer",
    "phase_one",
    "product_graph_bfs",
    "product_graph_into",
    "product_graph_ruleset",
    "quinone_formation",
    "random_path",
    "reactivity",
    "resolve",
    "to_curie",
]

@typing.final
class BoundPattern:
    r"""
    Python wrap of [`crate::bound_pattern::BoundPattern`].
    """
    @property
    def rule(self) -> RuleSet: ...
    @property
    def pattern(self) -> PatternInfo: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def rule_name(self) -> typing.Optional[builtins.str]: ...
    @property
    def curie(self) -> builtins.str: ...
    @property
    def iri(self) -> builtins.str: ...
    def __len__(self) -> builtins.int: ...
    def __contains__(self, key: builtins.str) -> builtins.bool: ...
    def __getitem__(self, key: builtins.int | builtins.str) -> BoundPattern: ...
    def metabolize(self, mol: ForestMol  |  mol.ForestMol, filter_rules: typing.Optional[collections.abc.Callable[[ForestMol  |  mol.ForestMol, RuleSet, PatternInfo], builtins.bool]] = None, filter_sites: typing.Optional[collections.abc.Callable[[ForestMol  |  mol.ForestMol, builtins.int, builtins.int], builtins.bool]] = None) -> builtins.list[Emission]:
        r"""
        Releases the GIL when no Python filters are passed.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class Emission:
    r"""
    One applied metabolize row (Python ``Emission``).
    """
    @property
    def pattern_name(self) -> builtins.str: ...
    @property
    def site(self) -> builtins.int: ...
    @property
    def site_atoms(self) -> builtins.list[builtins.int]:
        r"""
        Discovery site atoms on the reactant (bond ends / pair ends / atom).
        """
    @property
    def site_kind(self) -> typing.Literal["atom", "bond", "directed_bond", "atom_pair"]:
        r"""
        From the leaf rule's pattern ``site_kind`` (``atom`` / ``bond`` /
        ``directed_bond`` / ``atom_pair``) — how notebook SOM is drawn.
        """
    @property
    def site_tags(self) -> builtins.list[builtins.int]:
        r"""
        Trace labels for [`Self::site_atoms`] on the reactant (notebook SOM).
        """
    @property
    def reactant(self) -> ForestMol:
        r"""
        Mol the pattern was applied to (`site` indexes this mol).
        """
    def product_csmis(self) -> builtins.list[builtins.str]: ...
    def products(self) -> builtins.list[ForestMol]: ...
    def rule_path(self) -> builtins.list[typing.Optional[builtins.str]]: ...
    def to_dict(self) -> EmissionDict: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class EmissionDict(typing.TypedDict):
    r"""
    ``Emission.to_dict()``.
    """
    pattern_name: builtins.str
    site: builtins.int
    reactant: builtins.str
    r"""
    Reactant CSMI.
    """
    products: builtins.list[builtins.str]
    r"""
    Product CSMIs.
    """
    rule_path: builtins.list[typing.Optional[builtins.str]]
    r"""
    Leaf-first namespace names (``None`` for an unnamed set).
    """

class ForestMol:
    r"""
    Python class wrapping [`ForestMol`].
    
    `unsendable`: pyclass stays on one Python thread; payload `ForestMol` is Send
    (Arc caches) so pure-Rust doors can release the GIL.
    `#[new]` is `__init__`. Getters become Python properties.
    """
    @property
    def csmi(self) -> str:
        r"""
        Cached canonical SMILES. Interned so `mol.csmi is mol.csmi`.
        """
    @property
    def stable_csmi_key(self) -> typing.Optional[str]:
        r"""
        Fail-closed dedup key (Chematic `canonical_smiles_stable_key`).
        
        **Can return `None`.** Do not fall back to [`Self::csmi`] for HashSet /
        yield identity — skip CSMI dedup instead.
        """
    @property
    def formula(self) -> Formula: ...
    @property
    def stamp_end(self) -> builtins.int: ...
    def __new__(cls, smiles: builtins.str) -> ForestMol: ...
    def clear_structure(self) -> None: ...
    def copy(self) -> ForestMol: ...
    def edit_copy(self) -> ForestMol: ...
    def normalize_tautomer(self) -> tuple[ForestMol, builtins.bool]:
        r"""
        Chematic tautomer pick adopted with Forest tracing.
        
        Returns ``(ForestMol, changed)``.
        """
    def smarts_matches(self, smarts: builtins.str) -> builtins.list[builtins.dict[builtins.int, builtins.int]]: ...
    def atom_tags(self) -> builtins.list[typing.Optional[builtins.int]]:
        r"""
        Atom tags parallel to chematic indexes (`None` if unlabeled).
        """
    def trace_counts(self) -> tuple[builtins.int, builtins.int, builtins.int, builtins.int]:
        r"""
        Trace summary: `(stamp_end, n_survivors, n_born, n_untagged)`.
        
        Survivors are tags ``< stamp_end`` (present on the stamped root);
        born atoms were minted later in the shared tag lineage.
        """
    def stamp_origins(self) -> builtins.list[typing.Optional[builtins.int]]:
        r"""
        Root-stamp origin index for each atom (`None` if born / untagged).
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Formula:
    r"""
    Python-visible formula. Nested `#[pyclass]` wrap of [`Formula`].
    """
    @property
    def counts(self) -> builtins.dict[builtins.str, builtins.int]: ...
    @property
    def charge(self) -> builtins.int: ...

@typing.final
class GraphEdge:
    r"""
    One recorded parent→child hop (multipath slot on the child).
    """
    @property
    def child_index(self) -> builtins.int: ...
    @property
    def inbound_slot(self) -> builtins.int: ...
    @property
    def rule(self) -> builtins.str: ...
    @property
    def pattern_name(self) -> builtins.str: ...
    @property
    def site(self) -> builtins.int: ...
    @property
    def parent_index(self) -> builtins.int: ...
    @property
    def cleaves(self) -> builtins.bool: ...
    @property
    def kept_mol(self) -> ForestMol: ...
    @property
    def parent_mol(self) -> ForestMol:
        r"""
        Parent node mol (``site`` indexes this reactant, not the kept child).
        """
    def products_csmi(self) -> builtins.list[builtins.str]: ...
    def get_attr(self, key: builtins.str) -> typing.Optional[builtins.bool | builtins.int | builtins.str]: ...
    def set_attr(self, key: builtins.str, value: builtins.bool | builtins.int | builtins.str) -> None: ...
    def __contains__(self, key: builtins.str) -> builtins.bool: ...
    def __getitem__(self, key: builtins.str) -> builtins.bool | builtins.int | builtins.str: ...
    def __setitem__(self, key: builtins.str, value: builtins.bool | builtins.int | builtins.str) -> None: ...
    def to_dict(self) -> GraphEdgeDict: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class GraphEdgeDict(typing.TypedDict):
    r"""
    ``GraphEdge.to_dict()``.
    """
    child_index: builtins.int
    inbound_slot: builtins.int
    parent_index: builtins.int
    rule: builtins.str
    pattern_name: builtins.str
    site: builtins.int
    cleaves: builtins.bool
    attrs: builtins.dict[builtins.str, builtins.bool | builtins.int | builtins.str]

@typing.final
class GraphNode:
    r"""
    View of one molecule row in a [`MetabolicNetwork`].
    """
    @property
    def index(self) -> builtins.int: ...
    @property
    def csmi(self) -> builtins.str: ...
    @property
    def mol(self) -> ForestMol: ...
    @property
    def sealed(self) -> builtins.bool: ...
    @property
    def expanded(self) -> builtins.bool: ...
    def get_attr(self, key: builtins.str) -> typing.Optional[builtins.bool | builtins.int | builtins.str]:
        r"""
        Read a node attr (well-known keys include ``sealed``, ``expanded``).
        """
    def set_attr(self, key: builtins.str, value: builtins.bool | builtins.int | builtins.str) -> None:
        r"""
        Set a node attr (bool / int / str). Mutates the live network.
        """
    def __contains__(self, key: builtins.str) -> builtins.bool: ...
    def __getitem__(self, key: builtins.str) -> builtins.bool | builtins.int | builtins.str: ...
    def __setitem__(self, key: builtins.str, value: builtins.bool | builtins.int | builtins.str) -> None: ...
    def to_dict(self) -> GraphNodeDict:
        r"""
        Spine + attrs for notebooks / JSON (opt-in marshal).
        """
    def n_inbound(self) -> builtins.int: ...
    def inbound_edge(self, slot: builtins.int) -> GraphEdge: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class GraphNodeDict(typing.TypedDict):
    r"""
    ``GraphNode.to_dict()``.
    """
    index: builtins.int
    csmi: builtins.str
    sealed: builtins.bool
    expanded: builtins.bool
    attrs: builtins.dict[builtins.str, builtins.bool | builtins.int | builtins.str]

class HopDict(typing.TypedDict):
    r"""
    One search hop of ``PathOutcome.hops()``.
    """
    pattern_name: builtins.str
    site: builtins.int
    r"""
    Site on ``reactant``.
    """
    site_orbit: builtins.list[builtins.int]
    r"""
    Unique-edit orbit (includes ``site``).
    """
    reactant: builtins.str
    r"""
    CSMI the rule was applied to.
    """
    product: builtins.str
    r"""
    Kept fragment CSMI.
    """
    sides: builtins.list[builtins.str]
    r"""
    Cleaved-off fragment CSMIs.
    """
    rule: builtins.str
    r"""
    Leaf rule name (``""`` if unnamed).
    """
    rule_path: builtins.list[typing.Optional[builtins.str]]
    r"""
    Outer→leaf namespace names (``Default`` root omitted).
    """

class MaybeEntryDict(typing.TypedDict):
    r"""
    One cleavage-side bag of ``StepPlan.maybe()``.
    """
    site: builtins.list[builtins.int]
    side: builtins.str
    opens: builtins.list[builtins.list[builtins.int]]
    span_sites: builtins.list[builtins.list[builtins.int]]

@typing.final
class MetabolicNetwork:
    r"""
    Explored metabolic network (reactant root + hops). Mutated by search when
    passed as ``network=``.
    """
    @property
    def root_csmi(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls) -> MetabolicNetwork: ...
    def n_nodes(self) -> builtins.int: ...
    def n_edges(self) -> builtins.int: ...
    def reaches(self, target_csmi: builtins.str) -> builtins.bool: ...
    def prune_to_targets(self) -> builtins.int: ...
    def step_plan_between(self, from_idx: builtins.int, to_idx: builtins.int) -> StepPlan: ...
    def closest(self, target: builtins.str, k: builtins.int) -> builtins.list[tuple[builtins.str, builtins.int]]: ...
    def node_csmi(self, idx: builtins.int) -> builtins.str: ...
    def index_of(self, csmi: builtins.str) -> typing.Optional[builtins.int]: ...
    def root_idx(self) -> typing.Optional[builtins.int]: ...
    def n_rule_patterns(self) -> builtins.int: ...
    def mark_target(self, idx: builtins.int) -> None: ...
    def parents(self, csmi: builtins.str) -> builtins.list[builtins.str]: ...
    def children(self, csmi: builtins.str) -> builtins.list[builtins.str]: ...
    def node(self, idx: builtins.int) -> GraphNode:
        r"""
        Indexed node view (same graph handle; no clone of mols).
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> GraphNode: ...
    def target_csmis(self) -> builtins.list[builtins.str]:
        r"""
        Marked target CSMIs (sorted), for notebooks / summaries.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def missed(self, csmi: builtins.str, target: builtins.str) -> typing.Optional[ResidualDict]: ...

@typing.final
class PathCounters:
    @property
    def billed(self) -> builtins.int: ...
    @property
    def timed_out(self) -> builtins.bool: ...
    @property
    def diversity_repush(self) -> builtins.int: ...
    def to_dict(self) -> PathCountersDict: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class PathCountersDict(typing.TypedDict):
    r"""
    ``PathCounters.to_dict()``.
    """
    nodes: builtins.int
    mol_edits: builtins.int
    expansions: builtins.int
    billed: builtins.int
    dropped_duplicate_plan: builtins.int
    dropped_exact_plan: builtins.int
    dropped_skeleton_twin: builtins.int
    signal_contained_plan: builtins.int
    diversity_repush: builtins.int
    unstable_csmi_key: builtins.int
    timed_out: builtins.bool

@typing.final
class PathOutcome:
    r"""
    One reactant→target reach from ``find_path`` / ``find_path_partial``.
    
    Exact hits have ``residual_cost == 0``; ``find_path_partial`` may also
    return closest non-exact reaches (``residual_cost > 0``).
    """
    @property
    def smiles(self) -> builtins.str: ...
    @property
    def mol(self) -> ForestMol: ...
    @property
    def plan(self) -> StepPlan: ...
    @property
    def residual_cost(self) -> builtins.int:
        r"""
        Leftover disagreement with the target; ``0`` for exact hits.
        """
    @property
    def is_exact(self) -> builtins.bool:
        r"""
        ``residual_cost == 0``: reached the target.
        """
    def maybe(self) -> builtins.list[MaybeEntryDict]:
        r"""
        Cleavage Maybe bags (same as ``plan.maybe()``).
        """
    def hops(self) -> builtins.list[HopDict]:
        r"""
        Search hops (pattern / site on reactant / product) for pathway displays.
        """
    def residual(self) -> ResidualDict:
        r"""
        Full residual (cost, extra atoms, category hints); all-zero when exact.
        """
    def to_dict(self) -> PathOutcomeDict: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class PathOutcomeDict(typing.TypedDict):
    r"""
    ``PathOutcome.to_dict()``.
    """
    smiles: builtins.str
    steps: builtins.list[PlanStepDict]
    residual: ResidualDict
    r"""
    All-zero for exact hits; ``cost > 0`` only from ``find_path_partial``.
    """

@typing.final
class PatternInfo:
    r"""
    Python wrap of [`PatternInfo`]. Frozen data; `RuleSet` clones it in.
    """
    @property
    def name(self) -> builtins.str: ...
    @property
    def site_kind(self) -> typing.Literal["atom", "bond", "directed_bond", "atom_pair"]:
        r"""
        ``atom`` / ``bond`` / ``directed_bond`` / ``atom_pair``.
        """
    @property
    def smarts(self) -> builtins.str: ...
    @property
    def edit(self) -> builtins.str: ...
    @property
    def adds(self) -> typing.Optional[builtins.str]: ...
    @property
    def removes(self) -> typing.Optional[builtins.str]: ...
    @property
    def cleaves(self) -> builtins.bool: ...
    @property
    def methide(self) -> builtins.bool: ...
    def __new__(cls, name: builtins.str, smarts: builtins.str, edit: builtins.str, adds: typing.Optional[builtins.str] = None, removes: typing.Optional[builtins.str] = None, cleaves: builtins.bool = False, methide: builtins.bool = False) -> PatternInfo: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class PatternSummaryDict(typing.TypedDict):
    r"""
    Pattern summary in ``RandomPathOutcome.patterns()``.
    """
    name: builtins.str
    smarts: builtins.str
    cleaves: builtins.bool
    search_bias: builtins.int

class PlanStepDict(typing.TypedDict):
    r"""
    One elementary plan step (``rule`` + plan-atom ``site`` labels).
    """
    rule: builtins.str
    site: builtins.list[builtins.str]
    r"""
    Reactant indexes, or ``WillAdd(...)`` / ``AddedBy(...)`` labels.
    """

@typing.final
class RandomPathOutcome:
    @property
    def smiles(self) -> builtins.str: ...
    @property
    def path(self) -> builtins.list[builtins.str]: ...
    def to_dict(self) -> RandomPathOutcomeDict: ...
    def steps(self) -> builtins.list[RandomPathStepDict]: ...
    def patterns(self) -> builtins.list[PatternSummaryDict]: ...
    def __eq__(self, other: typing.Any) -> builtins.bool: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class RandomPathOutcomeDict(typing.TypedDict):
    r"""
    ``RandomPathOutcome.to_dict()``.
    """
    smiles: builtins.str
    path: builtins.list[builtins.str]
    steps: builtins.list[RandomPathStepDict]
    patterns: builtins.list[PatternSummaryDict]

class RandomPathStepDict(typing.TypedDict):
    r"""
    One hop of ``RandomPathOutcome.steps()``.
    """
    rule: builtins.str
    pattern: builtins.str
    site: builtins.list[builtins.int]
    products: builtins.list[builtins.str]
    chosen: builtins.int
    r"""
    Index into ``products`` the walk continued from.
    """

class ResidualDict(typing.TypedDict):
    r"""
    Leftover disagreement (``PathOutcome.residual()``, ``MetabolicNetwork.missed()``).
    """
    cost: builtins.int
    n_extra: builtins.int
    categories: builtins.list[builtins.str]
    r"""
    Soft category hints (conjugation-sized add, needs oxygen, …).
    """
    unresolvable: builtins.bool
    r"""
    True when no helper candidate resolves this residual.
    """

@typing.final
class RuleSet:
    r"""
    Python wrap of [`RuleSet`]. Patterns are copied into Rust at construction.
    """
    @property
    def name(self) -> typing.Optional[builtins.str]: ...
    @property
    def parity_exception(self) -> typing.Optional[builtins.str]:
        r"""
        Cross-language parity excuse, if any (see Rust `RuleSet::parity_exception`).
        """
    def __new__(cls, patterns: typing.Optional[typing.Sequence[PatternInfo]] = None, name: typing.Optional[builtins.str] = None) -> RuleSet: ...
    @staticmethod
    def hydroxylation() -> RuleSet: ...
    @staticmethod
    def o_dealkylation() -> RuleSet: ...
    @staticmethod
    def leaf(name: builtins.str) -> RuleSet:
        r"""
        Named leaf catalog rule (`Hydroxylation`, `Dealkylation`, …).
        """
    @staticmethod
    def catalog_names() -> builtins.list[builtins.str]:
        r"""
        Leaf names in catalog order.
        """
    @staticmethod
    def compose(sets: typing.Sequence[RuleSet], name: typing.Optional[builtins.str] = None) -> RuleSet: ...
    def __len__(self) -> builtins.int:
        r"""
        Direct member count (nested sets count as one member each).
        """
    def __contains__(self, key: builtins.str) -> builtins.bool: ...
    def __getitem__(self, key: builtins.int | builtins.str) -> RuleSet  |  BoundPattern:
        r"""
        Index by int or name: catalog → child ``RuleSet``; leaf → ``BoundPattern``.
        """
    def patterns(self) -> builtins.list[PatternInfo]:
        r"""
        Flat leaf patterns under this set (including nested members).
        """
    def metabolize(self, mol: ForestMol  |  mol.ForestMol, filter_rules: typing.Optional[collections.abc.Callable[[ForestMol  |  mol.ForestMol, RuleSet, PatternInfo], builtins.bool]] = None, filter_sites: typing.Optional[collections.abc.Callable[[ForestMol  |  mol.ForestMol, builtins.int, PatternInfo], builtins.bool]] = None) -> builtins.list[Emission]:
        r"""
        Run the owned members. `filter_rules` / `filter_sites` are optional Python
        callables; omit them and Rust `accept_all_*` runs with no GIL per site.
        
        Each row is `(pattern_name, site, products, rule_path)` where `rule_path`
        is leaf-first namespace names (`None` for an unnamed set).
        
        Releases the GIL when no Python filters are passed.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class StepPlan:
    r"""
    Elementary plan with precedes (Python ``StepPlan``).
    """
    def __len__(self) -> builtins.int: ...
    def n_linearizations(self) -> builtins.int: ...
    def linearizations(self) -> builtins.list[builtins.list[PlanStepDict]]:
        r"""
        Enumerate topological sorts under precedes (tiny plans).
        
        Each row is a list of ``{"rule", "site"}`` like plan steps. Caps at
        64 rows so accidental factorial explosions stay bounded.
        """
    def allows(self, site: typing.Optional[typing.Sequence[builtins.int]], side: typing.Optional[builtins.str]) -> builtins.bool: ...
    def maybe(self) -> builtins.list[MaybeEntryDict]:
        r"""
        Cleavage-side bags on this plan (`site` / `side` / `opens`).
        """
    def to_dict(self) -> StepPlanDict: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class StepPlanDict(typing.TypedDict):
    r"""
    ``StepPlan.to_dict()``.
    """
    steps: builtins.list[PlanStepDict]
    n_linearizations: builtins.int
    precedes: builtins.list[tuple[builtins.int, builtins.int]]
    r"""
    ``(before, after)`` step-index pairs.
    """
    maybe: builtins.list[MaybeEntryDict]

def dealkylation() -> RuleSet: ...

def default_ruleset() -> RuleSet: ...

def dehydrogenation() -> RuleSet: ...

def epoxidation() -> RuleSet: ...

def epoxide_opening() -> RuleSet: ...

def expand_iri(curie_or_iri: builtins.str) -> builtins.str: ...

def find_path(reactant: builtins.str, target: builtins.str, *, max_paths: builtins.int = 1, max_nodes: builtins.int = 800, use_atom_diff: builtins.bool = True, lazy_closer: builtins.bool = False, diversity: builtins.bool = False, drop_skeleton_twins: builtins.bool = True, score: builtins.str = 'log-neg-pc', timeout: typing.Optional[builtins.float] = None, network: typing.Optional[MetabolicNetwork] = None, normalize_tautomer: builtins.bool = False, invert_target_tautomer: builtins.bool = False) -> tuple[builtins.list[PathOutcome], PathCounters, MetabolicNetwork]:
    r"""
    Native chematic ``find_path`` (default ruleset).
    
    Returns ``(hits, counters, network)``; every hit is exact
    (``residual_cost == 0``). Search always records hops on a
    [`MetabolicNetwork`]: pass ``network=`` to extend a live graph, or omit it
    to get a fresh one back. Default ruleset is QuinoneFormation +
    EpoxideHydration + Tautomerization + PhaseOne core.
    
    Releases the GIL for the Rust search (including ``network=``).
    """

def find_path_partial(reactant: builtins.str, target: builtins.str, *, max_paths: builtins.int = 1, max_nodes: builtins.int = 800, use_atom_diff: builtins.bool = True, lazy_closer: builtins.bool = False, diversity: builtins.bool = False, drop_skeleton_twins: builtins.bool = True, score: builtins.str = 'log-neg-pc', timeout: typing.Optional[builtins.float] = None, network: typing.Optional[MetabolicNetwork] = None, normalize_tautomer: builtins.bool = False, invert_target_tautomer: builtins.bool = False) -> tuple[builtins.list[PathOutcome], PathCounters, MetabolicNetwork]:
    r"""
    Like ``find_path``, but also returns the closest non-exact reaches.
    
    Same return type as ``find_path``: ``(outcomes, counters, network)``.
    Exact hits come first (``residual_cost == 0``), then — only when they do
    not fill ``max_paths`` — closest partials by ascending ``residual_cost``;
    at most ``max_paths`` in total. Search always records hops on a
    [`MetabolicNetwork`] (pass ``network=`` to extend one).
    
    Releases the GIL for the Rust search (including ``network=``).
    """

def forest_xmet_sssom() -> builtins.str: ...

def hydrolysis() -> RuleSet: ...

def hydroxylation() -> RuleSet: ...

def leaf_rule(name: builtins.str) -> RuleSet:
    r"""
    Look up a sealed leaf by catalog name (`LEAF_CTORS`).
    
    Used by native↔Rust product parity over the shared coverage substrate pool.
    """

def n_dealkylation() -> RuleSet: ...

def normalize_tautomer(smiles: builtins.str) -> tuple[ForestMol, builtins.bool]:
    r"""
    Chematic tautomer pick adopted as a tagged [`ForestMol`].
    
    Returns ``(mol, changed)`` where ``mol`` is a :class:`ForestMol` and
    ``changed`` is whether the form differed from the input.
    """

def phase_one() -> RuleSet: ...

def product_graph_bfs(start: builtins.str, *, target: typing.Optional[builtins.str] = None, max_nodes: builtins.int = 256, max_depth: builtins.int = 6, ruleset: typing.Optional[RuleSet] = None, network: typing.Optional[MetabolicNetwork] = None) -> MetabolicNetwork:
    r"""
    BFS product exploration; returns a ``MetabolicNetwork``.
    
    .. warning::
    
       This can take a **very long time** and build a large graph even when
       ``max_nodes`` and ``max_depth`` are set. Use ``target=`` when you are
       exploring toward a single product CSMI.
    
    Default ``ruleset`` is ``product_graph_ruleset()`` — QuinoneFormation,
    EpoxideHydration, and Phase I core, **without** Tautomerization (unlike
    ``find_path``'s ``default_ruleset()``). Pass ``network=`` to extend an
    existing graph (same object as ``find_path`` ``network=``).
    
    Releases the GIL for the Rust BFS (including ``network=``).
    """

def product_graph_into(network: MetabolicNetwork, start: builtins.str, *, target: typing.Optional[builtins.str] = None, max_nodes: builtins.int = 256, max_depth: builtins.int = 6, ruleset: typing.Optional[RuleSet] = None) -> None: ...

def product_graph_ruleset() -> RuleSet: ...

def quinone_formation() -> RuleSet: ...

def random_path(reactant: builtins.str, seed: builtins.int, *, max_steps: builtins.int = 1, ruleset: typing.Optional[RuleSet] = None, skip_multicomponent: builtins.bool = False, skip_seen: builtins.bool = False) -> RandomPathOutcome:
    r"""
    Seeded random walk: apply up to ``max_steps`` rules. Returns
    [`RandomPathOutcome`].
    
    Default ruleset is PhaseOne. Pass a ``RuleSet`` to override.
    ``skip_multicomponent`` / ``skip_seen`` map to [`PathwayOptions`] (off by
    default; same knobs for StepSequence / PathOutcome ``apply``).
    
    Releases the GIL for the Rust walk.
    """

def reactivity() -> RuleSet: ...

def resolve(id: builtins.str) -> RuleSet  |  BoundPattern: ...

def to_curie(iri: builtins.str) -> builtins.str: ...

